---
title: "ADNI datasets"
author: "Shahzad"
date: "`r format(Sys.Date(), '%A, %d %B %Y')`"
css: layout.css
output:
  html_document:
    number_sections: no
    code_folding: hide
    theme: united
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---

<!-- Defining font size for the document -->

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      message = F,
                      warning = F,
                      eval = T)
# load packages
pacman::p_load(data.table,
               here,
               gtsummary,
               flextable,
               rio,
               DT,
               UpSetR,
               tidyverse)
```
# List the Biomarker files in the folders 
```{r}
# Set your ADNI dataset path
data_path <- "/home/rstudio/new_direc/data_unziped"
#list.files(file.path(data_path, "Biospecimen"), full.names = TRUE)
#list.files(file.path(data_path, "Enrollment"), full.names = TRUE)

biomarker_file <- file.path(data_path, "Biospecimen", "UPENNBIOMK_MASTER_FINAL_20May2023.csv")
diagnosis_file <- file.path(data_path, "Assessments", "DXSUM_PDXCONV_ADNIALL_19May2023.csv")

# Load data
biomarkers <- read_csv(biomarker_file)
diagnosis <- read_csv(diagnosis_file)

```

```{r}
# Code for preprocessing used from published project https://doi.org/10.1093/brain/awae176
biomarkers <- subset(upennbio, RUNDATE>=as.Date("2016-11-17"))

#go through each RID and compute median of values at duplicate time points
biomarkers$ABETA42  <- as.double(gsub("<","", gsub(">","", biomarkers$ABETA42)))
biomarkers$TAU  <- as.double(gsub("<","", gsub(">","", biomarkers$TAU)))
biomarkers$PTAU <- as.double(gsub("<","", gsub(">","", biomarkers$PTAU)))

tag <- apply(biomarkers,1, function(x){ paste(as.integer(x["RID"]), x["VISCODE2"], sep="_") })

biomarkers_clean <- data.frame(t(sapply(unique(tag), function(tt){
  tmp <- biomarkers[tag == tt,]
  out_a <- tmp[1, c("PHASE","RID","VISCODE2","EXAMDATE")]
  out_b <- apply(tmp[,c("ABETA40","ABETA42","TAU","PTAU")],2, median, na.rm=T)
  return(unlist(c(out_a, out_b)))
})))

for ( bioM in c("RID","ABETA40","ABETA42","TAU","PTAU")){
  biomarkers_clean[[bioM]] <- as.double(biomarkers_clean[[bioM]])
}
```

# Read the biomarker files and calculate the AT categories for the biomarkers
```{r}
# Converting the variables to numeric 
biomarkers_clean$ABETA42<-as.numeric(biomarkers_clean$ABETA42)
biomarkers_clean$TAU<-as.numeric(biomarkers_clean$TAU)
biomarkers_clean$PTAU<-as.numeric(biomarkers_clean$PTAU)
# Creating an ATN category profiles of individuals 
biomarkers_clean$ATN_category2<-NA
biomarkers_clean$ATN_category2[biomarkers_clean$ABETA42>976.6 & biomarkers_clean$PTAU<21.8]<-'A_T_'
biomarkers_clean$ATN_category2[biomarkers_clean$ABETA42<976.6 & biomarkers_clean$PTAU<21.8]<-'A+T_'
biomarkers_clean$ATN_category2[biomarkers_clean$ABETA42<976.6 & biomarkers_clean$PTAU>21.8]<-'A+T+'

  
```
# Add the diagnosis information

```{r}

dxsum<-read_csv(file.path(data_path, "Assessments", "DXSUM_PDXCONV_ADNIALL_19May2023.csv"))
registry <- read_csv(file.path(data_path, "Enrollment", "REGISTRY_19May2023.csv"))
arm<-read_csv(file.path(data_path, "Enrollment", "ARM_19May2023.csv"))

dxsum$DXCHANGE <- NA
# Assign based on conditions
dxsum$DXCHANGE[dxsum$DXCONV == 0 & dxsum$DXCURREN == 1] <- 1
dxsum$DXCHANGE[dxsum$DXCONV == 0 & dxsum$DXCURREN == 2] <- 2
dxsum$DXCHANGE[dxsum$DXCONV == 0 & dxsum$DXCURREN == 3] <- 3
dxsum$DXCHANGE[dxsum$DXCONV == 1 & dxsum$DXCONTYP == 1] <- 4
dxsum$DXCHANGE[dxsum$DXCONV == 1 & dxsum$DXCONTYP == 3] <- 5
dxsum$DXCHANGE[dxsum$DXCONV == 1 & dxsum$DXCONTYP == 2] <- 6
dxsum$DXCHANGE[dxsum$DXCONV == 2 & dxsum$DXREV == 1] <- 7
dxsum$DXCHANGE[dxsum$DXCONV == 2 & dxsum$DXREV == 2] <- 8
dxsum$DXCHANGE[dxsum$DXCONV == 2 & dxsum$DXREV == 3] <- 9


# Identify variable to keep for merged data
armVars <- c("RID","Phase","ARM","ENROLLED")
dxsumVars <- c("RID","Phase", "VISCODE2","DXCHANGE","VISCODE")
# merge data
dxarm <- merge(dxsum[dxsumVars], arm[armVars], by=c("RID","Phase"))
# baseline data
baseData <- dxarm[dxarm$VISCODE2=='bl' & dxarm$ENROLLED%in% c(1,2,3),]

# assign baseline diagnosis
baseData$baselineDx<-NA
baseData$baselineDx[(baseData$DXCHANGE %in% c(1,7,9)) & baseData$ARM != 11 ] = 1
baseData$baselineDx[(baseData$DXCHANGE %in% c(1,7,9)) & baseData$ARM == 11 ] = 2
baseData$baselineDx[(baseData$DXCHANGE %in% c(2,4,8)) & baseData$ARM == 10 ] = 3
baseData$baselineDx[(baseData$DXCHANGE %in% c(2,4,8)) & baseData$ARM != 10 ] = 4
baseData$baselineDx[(baseData$DXCHANGE %in% c(3,5,6))] = 5
# merge baseline diagnosis
baseVars <- c("RID","baselineDx")
dxarm <- merge( dxarm, baseData[baseVars],by=c("RID"))

# Merging with the registry files 
# identify variable to keep for merged data
regVars <-c("RID", "Phase", "VISCODE", "VISCODE2",
            "EXAMDATE", "PTSTATUS", "RGCONDCT", "RGSTATUS",
            "VISTYPE")
# merge data
dxarm_reg <-left_join(dxarm,registry[regVars], by=c("RID", "Phase", "VISCODE"))

# Merging the DXCHANGE AND baselineDx variables with the main df.
df<-dxarm_reg %>% 
  mutate(RID_VISCODE2=paste0(RID,'_',VISCODE2.x)) %>% 
  select(RID_VISCODE2,DXCHANGE,baselineDx) %>% 
  merge(biomarkers_Batch9,by='RID_VISCODE2',all.y = T)

```

# Add date to calculate the progression analysis

```{r}
# Upload the registry dataset 
registry <- read_csv(file.path(data_path, "Enrollment", "REGISTRY_19May2023.csv"))
registry_dates <- registry %>%
  select(RID, VISCODE2, EXAMDATE)

# Merge with your df
df_time <- df %>%
  left_join(registry_dates, by = c("RID", "VISCODE2"))

# Baseline data 
baseline_dates <- df_time %>%
  filter(VISCODE2 == "bl") %>%
  select(RID, baseline_date = EXAMDATE)

# Merge date information with full dataset with dates 
df_days <- df_time %>%
  left_join(baseline_dates, by = "RID") %>%
  mutate(days_since_bl = as.numeric(difftime(EXAMDATE, baseline_date, units = "days")))
```

# Add APOE information
```{r}
adnimerg<-read_csv(file.path(data_path, "Study_Info", "ADNIMERGE_19May2023.csv"))
df<-adnimerg %>% 
  select(RID,VISCODE,APOE4,PTGENDER,AGE) %>% 
  mutate(RID_VISCODE2 = paste0(RID,'_',VISCODE)) %>% 
  select(-RID,-VISCODE) %>% 
  merge(., df_days,by='RID_VISCODE2', all.y = T)

```

```{r}
df<-df %>% arrange(RID, EXAMDATE)
df$coversion_mci_ad<-NA
df$coversion_mci_ad[which(df$DXCHANGE==5)]<-1
df$coversion_mci_ad[which(df$DXCHANGE==2)]<-0

# Select only MCI to AD converters which first appeared in the follow-up: RID and RID_viscode2 ids 
ID_mci_to_AD<-df %>% filter(coversion_mci_ad==1) %>% group_by(RID) %>% mutate(serial=row_number()) %>% filter(serial==1) %>% pull(RID_VISCODE2)
RID_mci_to_AD<-df %>% filter(coversion_mci_ad==1) %>% group_by(RID) %>% mutate(serial=row_number()) %>% filter(serial==1) %>% pull(RID)
# Select only MCI to MCI participants which never converted to AD until the last follow-up using RID 
ID_mci_to_mci<- df %>% filter(coversion_mci_ad==0 ) %>% 
  group_by(RID) %>% mutate(serial=row_number()) %>% 
  filter(!RID%in%RID_mci_to_AD) %>% 
  filter(serial==max(serial)) %>% 
  pull(RID_VISCODE2)

# Pull the IDs from both cases and controls and select only those with greater than 0 follow-up years and log transform the variable 
df_mci_ad<-df %>% filter(RID_VISCODE2%in%ID_mci_to_AD | RID_VISCODE2%in%ID_mci_to_mci)
# In the final dataset, there are some participants which are Normal (not MCI) as per baselineDx variables: 4041_m24 and 4506_m24. 
res.cox<-coxph(Surv(df_days, coversion_mci_ad) ~ 1 + APOE4, data = df_mci_ad)
summary(res.cox)
```



# Creating the dataset for the survival analysis 
```{r}
# Only keep EMCI/LMCI at baseline
mci_baseline <- df %>%
  filter(VISCODE2 == "bl", baselineDx %in% c(3, 4)) %>%
  select(RID, baselineDx, ABETA42, TAU, PTAU, ATN_category2, baseline_date, APOE4, PTGENDER,AGE)

# Get time to AD conversion (DXCHANGE == 5)
conversion <- df %>%
  filter(DXCHANGE == 5, !is.na(days_since_bl)) %>%
  group_by(RID) %>%
  summarise(time_to_event = min(days_since_bl), event = 1)

censored <- df %>%
  filter(DXCHANGE == 2, !is.na(days_since_bl)) %>%
  group_by(RID) %>%
  summarise(time_to_event = max(days_since_bl), event = 0)

# Combine
surv_data <- bind_rows(conversion, censored) %>%
  left_join(mci_baseline, by = "RID") %>%
  mutate(time_to_event_months = time_to_event / 30.44)
```


```{r}


```

# Survial analysis
```{r}
library(survival)
library(survminer)
fit <- survfit(Surv(time_to_event_months, event) ~ APOE4, data = surv_data)
ggsurvplot(fit,
           data = surv_data,
           risk.table = TRUE,
           pval = TRUE,
           xlab = "Time from Baseline (months)",
           ylab = "Survival Probability (MCI âž AD)",
           title = "Progression from MCI to AD by ATN Category",
           palette = "Dark2")
```






